=== PolexRufous/XMLParsing/XMLParser/files/simpleXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema xmlns="http://www.w3.org/2001/XMLSchema" 
		xmlns:tns="http://www.example.org/simpleXMLSchema" 
		targetNamespace="http://www.example.org/simpleXMLSchema"
		elementFormDefault="qualified">
		
		<element name="computer">
			<complexType>
				<sequence>
					<element name="device" type="tns:Device" minOccurs="1" maxOccurs="unbounded" />
				</sequence>
			</complexType>
		</element>
		
		<complexType name="Device">
			<sequence>
				<element name="name" type="string" />
				<element name="origin" type="string" />
				<element name="price" type="positiveInteger" />
				<element ref="tns:abstractType" minOccurs="1" maxOccurs="10" />
			</sequence>
			<attribute name="id" type="tns:idType" use="required" />
			<attribute name="critical" type="boolean" default="false" />
		</complexType>
		
		<element name="abstractType" type="tns:AbstractType" abstract="true" ></element>
		<element name="internalType" type="tns:Internal" substitutionGroup="tns:abstractType"></element>
		<element name="externalType" type="tns:External" substitutionGroup="tns:abstractType"></element>
		
		<simpleType name="idType">
			<restriction base="ID">
				<pattern value="([A-Z]){1}([a-z0-9]){1,12}" />
			</restriction>
		</simpleType>
		
		<complexType name="AbstractType">
			<sequence>
				<element name="cooler" type="boolean" />
				<element name="energy" type="double" />
				<element name="group" type="tns:Group" />
			</sequence>
		</complexType>
		
		<simpleType name="Group">
			<restriction base="string">
				<enumeration value="audio" />
				<enumeration value="video" />
				<enumeration value="input" />
				<enumeration value="print" />
				<enumeration value="data" />
			</restriction>
		</simpleType>
		
		<complexType name="Internal">
			<complexContent>
				<extension base="tns:AbstractType">
					<sequence>
						<element name="port" type="tns:intPort" />
					</sequence>
				</extension>
			</complexContent>
		</complexType>
		
		<complexType name="External">
			<complexContent>
				<extension base="tns:AbstractType">
					<sequence>
						<element name="port" type="tns:extPort" />
					</sequence>
					<attribute name="extPower" type="boolean" use="optional" default="false" />
				</extension>
			</complexContent>
		</complexType>
		
				
		<simpleType name="extPort">
			<restriction base="string">
				<enumeration value="LPT" />
				<enumeration value="USB" />
				<enumeration value="COM" />
				<enumeration value="VGA" />
				<enumeration value="SVGA" />
				<enumeration value="JET" />
			</restriction>
		</simpleType>
		
		<simpleType name="intPort">
			<restriction base="string">
				<enumeration value="PCI" />
				<enumeration value="IDE" />
				<enumeration value="SATA" />
				<enumeration value="DIMM" />
				<enumeration value="SIMM" />
				<enumeration value="PCIE" />
				<enumeration value="Socket" />
				<enumeration value="Base" />
			</restriction>
		</simpleType>
		
</schema>

=== PolexRufous/XMLParsing/XMLParser/files/newTestXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:computer	xmlns:tns="http://www.example.org/simpleXMLSchema" 
				xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				xsi:schemaLocation="http://www.example.org/simpleXMLSchema simpleXMLSchema.xsd ">
  <tns:device id="idvalue0">
    <tns:name>tns:name</tns:name>
    <tns:origin>tns:origin</tns:origin>
    <tns:price>1</tns:price>
    <tns:internalType>
      <tns:cooler>true</tns:cooler>
      <tns:energy>0.0</tns:energy>
      <tns:group>audio</tns:group>
      <tns:port>PCI</tns:port>
    </tns:internalType>
  </tns:device>
</tns:computer>

=== PolexRufous/XMLParsing/XMLParser/files/simpleExample.xml
<?xml version="1.0" encoding="UTF-8"?>

<computer	xmlns="http://www.example.org/simpleXMLSchema"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://www.example.org/simpleXMLSchema simpleXMLSchema.xsd">
			
	<device id="Hddrive1" critical="true">
		<name>SeagateBaracuda250GB</name>
		<origin>China</origin>
		<price>150</price>
		<internalType>
			<cooler>false</cooler>
			<energy>5</energy>
			<group>data</group>
			<port>SATA</port>
		</internalType>
		<externalType extPower="true">
			<cooler>true</cooler>
			<energy>7.3</energy>
			<group>data</group>
			<port>USB</port>
		</externalType>
	</device>
	
	<device id="Cdrive1">
		<name>AsusDVD32x</name>
		<origin>China</origin>
		<price>67</price>
		<externalType extPower="false">
			<cooler>true</cooler>
			<energy>6</energy>
			<group>input</group>
			<port>USB</port>
		</externalType>
	</device>
	
	<device id="Memory1">
		<name>AsusMemory4GB</name>
		<origin>China</origin>
		<price>81</price>
		<internalType>
			<cooler>false</cooler>
			<energy>3</energy>
			<group>data</group>
			<port>DIMM</port>
		</internalType>
	</device>
	
	<device id="Memory2">
		<name>AsusMemory4GB</name>
		<origin>China</origin>
		<price>81</price>
		<internalType>
			<cooler>false</cooler>
			<energy>3</energy>
			<group>data</group>
			<port>DIMM</port>
		</internalType>
	</device>
	
	<device id="Mainboard">
		<name>AsusMainSuperCool</name>
		<origin>China</origin>
		<price>137</price>
		<internalType>
			<cooler>true</cooler>
			<energy>9</energy>
			<group>data</group>
			<port>Base</port>
		</internalType>
	</device>
	
	<device id="Video1">
		<name>Huangao Video 512MB</name>
		<origin>China</origin>
		<price>143</price>
		<internalType>
			<cooler>true</cooler>
			<energy>11</energy>
			<group>video</group>
			<port>PCIE</port>
		</internalType>
	</device>
	
	
	<device id="Sound1">
		<name>Sven audio 18Vt</name>
		<origin>China</origin>
		<price>17</price>
		<externalType extPower="true">
			<cooler>false</cooler>
			<energy>18</energy>
			<group>audio</group>
			<port>JET</port>
		</externalType>
	</device>
	
	
	<device id="Screen1">
		<name>LG 19"</name>
		<origin>China</origin>
		<price>156</price>
		<externalType extPower="true">
			<cooler>true</cooler>
			<energy>23</energy>
			<group>video</group>
			<port>VGA</port>
		</externalType>
	</device>
	
	<device id="Processor1">
		<name>Intel Core i18</name>
		<origin>China</origin>
		<price>214</price>
		<internalType>
			<cooler>true</cooler>
			<energy>11</energy>
			<group>data</group>
			<port>Socket</port>
		</internalType>
	</device>
	
</computer>
